# Preprocesado de datos

## Creación de conjunto de entrenamiento y pruebas

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv("precios_casas.csv")
X = df.iloc[:,1:].values
y = df.iloc[:,0].values
print(X)
entX, pruX, enty, pruy = train_test_split(X, y, test_size=0.2, random_state=100)

[[313000.0 3.0 1.5 ... 'Shoreline' 'WA 98133' 'USA']
 [2384000.0 5.0 2.5 ... 'Seattle' 'WA 98119' 'USA']
 [342000.0 3.0 2.0 ... 'Kent' 'WA 98042' 'USA']
 ...
 [416904.166667 3.0 2.5 ... 'Renton' 'WA 98059' 'USA']
 [203400.0 4.0 2.0 ... 'Seattle' 'WA 98178' 'USA']
 [220600.0 3.0 2.5 ... 'Covington' 'WA 98042' 'USA']]


## Manejo de datos ausentes

In [48]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [148]:
df = pd.DataFrame([
        ['1', 1, 30],
        ['2', 1, 32],
        ['3', 0]],               
)
df.columns = ['codigo','credito','edad']

In [149]:
df.replace('?', np.nan, inplace=True) #esto es solo una prueba

In [150]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(df.values)
imp_datos = imp.transform(df.values)

## Manejo de datos categóricos

In [243]:
df = pd.DataFrame([
        ['M', 30, 'Amarillo','Clase 1'],
        ['P', 28 , 'Azul','Clase 2'],
        ['J', 21, 'Rojo', 'Clase 1']],               
)
df.columns = ['nombre','edad','color', 'etiqueta']
dfAux = df

In [244]:
from sklearn.preprocessing import LabelEncoder
le_clase = LabelEncoder()
y = le_clase.fit_transform(df.etiqueta)
print(y)

[0 1 0]


In [245]:
clase_inv = le_clase.inverse_transform(y)
print(clase_inv)

['Clase 1' 'Clase 2' 'Clase 1']


In [246]:
from sklearn.preprocessing import OneHotEncoder
le_color = LabelEncoder()
ohe_color = OneHotEncoder(categories='auto')
df['color_cod'] = le_color.fit_transform(df.color)
print(df)

  nombre  edad     color etiqueta  color_cod
0      M    30  Amarillo  Clase 1          0
1      P    28      Azul  Clase 2          1
2      J    21      Rojo  Clase 1          2


In [247]:
datos_ohe = ohe_color.fit_transform(df.color_cod.values.reshape(-1,1)).toarray()
dfOneHot = pd.DataFrame(datos_ohe, columns = ["Color_"+str(int(i)) for i in range(len(df.color))]) 
df = pd.concat([df, dfOneHot], axis=1)
df

nombre  edad     color etiqueta  color_cod  Color_0  Color_1  Color_2
0      M    30  Amarillo  Clase 1          0      1.0      0.0      0.0
1      P    28      Azul  Clase 2          1      0.0      1.0      0.0
2      J    21      Rojo  Clase 1          2      0.0      0.0      1.0

In [248]:
df= df.drop(['color','color_cod'], axis=1)
df

nombre  edad etiqueta  Color_0  Color_1  Color_2
0      M    30  Clase 1      1.0      0.0      0.0
1      P    28  Clase 2      0.0      1.0      0.0
2      J    21  Clase 1      0.0      0.0      1.0

In [250]:
df = pd.get_dummies(data=dfAux, columns=["color"], drop_first=True)
df= df.drop(['color_cod'], axis=1)
df

nombre  edad etiqueta  color_Azul  color_Rojo
0      M    30  Clase 1           0           0
1      P    28  Clase 2           1           0
2      J    21  Clase 1           0           1

## Escalamiento de características

In [251]:
def normalizar(columna):
     x_norma = (columna - columna.min()) / (columna.max() - columna.min()) 
     return x_norma

In [252]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df = pd.read_csv("precios_casas.csv")
esc = MinMaxScaler()
X_ent = esc.fit_transform(df.price.values.reshape(-1,1))
print(X_ent)

[[0.01177134]
 [0.08965777]
 [0.01286198]
 ...
 [0.01567898]
 [0.00764949]
 [0.00829635]]


In [253]:
def estandarizar(columna):
    x_estandar = ( columna - columna.mean())  / columna.std()
    return x_estandar

In [254]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
df = pd.read_csv("precios_casas.csv")
est = StandardScaler()
X_ent = est.fit_transform(df.price.values.reshape(-1,1))
print(X_ent)

[[-0.42386353]
 [ 3.2495981 ]
 [-0.37242442]
 ...
 [-0.23956224]
 [-0.61826787]
 [-0.58775916]]
